name: CI
on: push
jobs:
  buildAndTest:
    name: build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: taiki-e/install-action@just
      - name: Build and Test
        run: |
          just test
