name: CI
on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  XCODE_APP_NAME: Xcode_16.3.app

jobs:
  quality:
    name: quality
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: taiki-e/install-action@just

      - name: SwiftLint
        run: |
          just lint

      # - name: Build Example app
      #   env:
      #     DESTINATION: ${{ matrix.destination }}
      #   run: |
      #     just build-example

  test:
    name: test
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3

      - uses: taiki-e/install-action@just

      - name: Select Xcode version
        run: |
          echo "listing available Xcode versions:"
          ls -d /Applications/Xcode*

          sudo xcode-select --switch /Applications/$XCODE_APP_NAME/Contents/Developer

      - name: Test
        run: |
          just test

      - name: Export coverage
        run: |
          just export-code-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.lcov
          fail_ci_if_error: true
          verbose: true
